cart_view:
    path:      /cart/view
    defaults:  { _controller: MobileCartCoreBundle:Frontend/Cart:index }
    methods:  [GET]

cart_init:
    path:      /cart/init
    defaults:  { _controller: MobileCartCoreBundle:Frontend/Cart:init }
    methods:  [POST]

cart_add_item:
    path:      /cart/product/add
    defaults:  { _controller: MobileCartCoreBundle:Frontend/Cart:addProduct }
    methods:  [POST]

cart_shipment_add:
    path:     /cart/shipment/add
    defaults: { _controller: MobileCartCoreBundle:Frontend/Cart:addShipment }
    methods:  [POST]

cart_add_discount:
    path:     /cart/discount/add
    defaults: { _controller: MobileCartCoreBundle:Frontend/Cart:addDiscount }
    methods:  [GET,POST]

cart_update_qtys:
    path: /cart/product/update-qtys
    defaults: { _controller: MobileCartCoreBundle:Frontend/Cart:updateQtys }
    methods:  [POST]

cart_remove_item:
    path: /cart/product/remove
    defaults: { _controller: MobileCartCoreBundle:Frontend/Cart:removeProduct }
    methods:  [GET,POST]

cart_remove_items:
    path: /cart/products/remove
    defaults: { _controller: MobileCartCoreBundle:Frontend/Cart:removeProducts }
    methods:  [POST]

cart_totals:
    path: /cart/totals
    defaults: { _controller: MobileCartCoreBundle:Frontend/Cart:totals }
    methods:  [GET]

cart_checkout:
    path: /cart/checkout
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Checkout:index' }
    methods: [GET]

cart_checkout_section:
    path: /cart/checkout/{section}
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Checkout:viewSection' }
    methods: [GET]

cart_checkout_update_section:
    path: /cart/checkout/update/{section}
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Checkout:updateSection' }
    methods: [POST]

cart_checkout_confirm_order:
    path: /cart/checkout/order/confirm
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Checkout:confirmOrder' }
    methods: [GET]

cart_checkout_submit_order:
    path: /cart/checkout/order/submit
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Checkout:submitOrder' }
    methods: [POST]

cart_checkout_success:
    path: /cart/checkout/order/success
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Checkout:success' }
    methods: [GET]

cart_currency:
    path: /currency/{code}
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Currency:index' }
    methods:  [GET, POST]

cart_locale:
    path: /locale/{code}
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Locale:index' }
    methods:  [GET, POST]

#cart_webhook:
#    path: /webhook
#    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Webhook:index' }

#api_shipping_rates:
#    path: /api/shipping/
#    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Shipping:rates' }
#    methods: [GET]

cart_image_index:
    path: /image
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Image:index' }
    methods: [GET]

cart_image_upload:
    path: /image/upload
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Image:upload' }
    methods: [PUT]

cart_image_upload_base64:
    path: /image/upload/base64
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Image:uploadBase64' }
    methods: [POST]

cart_contact:
    path: /contact
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Contact:index' }
    methods: [GET]

cart_contact_post:
    path: /contact/post
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Contact:post' }
    methods: [POST]

cart_contact_thankyou:
    path: /contact/thankyou
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Contact:thankyou' }
    methods: [GET]
