_home:
    path:  /
    defaults: { _controller: MobileCartCoreBundle:Frontend/Home:index }

#url_rewrite:
#    resource: .
#    type: rewrite

login:
    pattern: /login
    defaults: { _controller: MobileCartCoreBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    path: /logout

MobileCartCoreBundle:
    resource: "@MobileCartCoreBundle/Controller/"
    type:     annotation
    prefix:   /
