_home:
    path:  /
    defaults: { _controller: MobileCartCoreBundle:Frontend/Home:index }

#url_rewrite:
#    resource: .
#    type: rewrite

login_route:
    path: /login
    defaults: { _controller: MobileCartCoreBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

cart_frontend_cart:
    resource: "@MobileCartCoreBundle/Resources/config/routing_frontend_cart.yml"
    prefix: /

cart_frontend_catalog:
    resource: "@MobileCartCoreBundle/Resources/config/routing_frontend_catalog.yml"
    prefix: /

cart_frontend_customer:
    resource: "@MobileCartCoreBundle/Resources/config/routing_frontend_customer.yml"
    prefix: /

cart_admin:
    resource: "@MobileCartCoreBundle/Resources/config/routing_admin.yml"
    prefix: /
