customer_register:
    path: /account/register
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:register' }
    methods: [GET]

customer_register_post:
    path: /account/create
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:registerPost' }
    methods: [POST]

customer_check_email:
    path: /account/check-email
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:registerCheckEmail' }
    methods: [GET]

customer_register_confirm:
    path: /account/confirm
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:registerConfirm' }
    methods: [GET]

customer_forgot_password:
    path: /account/forgot-password
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:forgotPassword' }
    methods: [GET]

customer_forgot_password_post:
    path: /account/forgot-password
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:forgotPasswordPost' }
    methods: [POST]

customer_forgot_password_success:
    path: /account/forgot-password/success
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:forgotPasswordSuccess' }
    methods: [GET]

customer_update_password:
    path: /account/update-password
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:updatePassword' }
    methods: [GET]

customer_update_password_post:
    path: /account/update-password
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:updatePasswordPost' }
    methods: [POST]

customer_profile:
    path: /customer/profile
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:profile' }
    methods: [GET]

customer_update:
    path: /customer/update
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:update' }
    methods: [PUT]

customer_orders:
    path: /customer/orders
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:orderHistory' }
    methods: [GET]

customer_order:
    path: /customer/order/{id}
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\Customer:orderView' }
    methods: [GET]

customer_addresses:
    path: /customer/addresses
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\CustomerAddress:index' }
    methods: [GET]

customer_address_new:
    path: /customer/address/new
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\CustomerAddress:new' }
    methods: [GET]

customer_address_create:
    path: /customer/address/create
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\CustomerAddress:create' }
    methods: [POST]

customer_address_edit:
    path: /customer/address/{id}/edit
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\CustomerAddress:edit' }
    methods: [GET]

customer_address_update:
    path: /customer/address/{id}/update
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\CustomerAddress:update' }
    methods: [PUT]

customer_address_delete:
    path: /customer/address/{id}/delete
    defaults: { _controller: 'MobileCartCoreBundle:Frontend\CustomerAddress:delete' }
    methods: [DELETE]
