<?php

namespace MobileCart\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemVarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemVarRepository
    extends EntityRepository
    implements CartRepositoryInterface
{
    /**
     * @return array
     */
    public function getSortableFields()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'code' => 'Code',
            'url_token' => 'URL Token',
            'datatype' => 'Data Type',
            'form_input' => 'Form Input',
            'is_required' => 'Is Required',
            'is_displayed' => 'Is Displayed',
        ];
    }

    /**
     * @return array
     */
    public function getFilterableFields()
    {
        return array(
            array(
                'code'  => 'id',
                'label' => 'ID',
                'type'  => 'number',
            ),
            array(
                'code'  => 'name',
                'label' => 'Name',
                'type'  => 'string',
            ),
            array(
                'code'  => 'code',
                'label' => 'Code',
                'type'  => 'string',
            ),
            array(
                'code'  => 'url_token',
                'label' => 'URL Token',
                'type'  => 'string',
            ),
            array(
                'code'  => 'datatype',
                'label' => 'Data Type',
                'type'  => 'string',
            ),
            array(
                'code'  => 'form_input',
                'label' => 'Form Input',
                'type'  => 'string',
            ),
        );
    }

    /**
     * @return bool
     */
    public function isEAV()
    {
        return false;
    }

    /**
     * @return mixed|string
     */
    public function getSearchField()
    {
        return 'name';
    }

    /**
     * @return int|mixed
     */
    public function getSearchMethod()
    {
        return self::SEARCH_METHOD_LIKE;
    }
}
