<?php

namespace MobileCart\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

use MobileCart\CoreBundle\Constants\EntityConstants;

/**
 * UrlRewriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRewriteRepository
    extends EntityRepository
    implements CartRepositoryInterface
{

    /**
     * @return bool
     */
    public function isEAV()
    {
        return false;
    }

    /**
     * @return array
     */
    public function getSortableFields()
    {
        return [
            'id' => 'ID',
            'object_type' => 'Object Type',
            'object_action' => 'Object Action',
            'request_uri' => 'Request URI',
            'redirect_url' => 'Redirect URL',
        ];
    }

    /**
     * @return array
     */
    public function getFilterableFields()
    {
        return [
            [
                'code'  => 'id',
                'label' => 'ID',
                'type'  => 'number',
            ],
            [
                'code' => 'object_type',
                'label' => 'Object Type',
                'type' => 'string',
                'choices' => [
                    [
                        'value' => EntityConstants::PRODUCT,
                        'label' => 'Product'
                    ],
                    [
                        'value' => EntityConstants::CONTENT,
                        'label' => 'Content',
                    ],
                    [
                        'value' => EntityConstants::CATEGORY,
                        'label' => 'Category',
                    ],
                ],
            ],
            [
                'code' => 'object_action',
                'label' => 'Object Action',
                'type' => 'string',
                'choices' => [
                    [
                        'value' => 'list',
                        'label' => 'List',
                    ],
                    [
                        'value' => 'view',
                        'label' => 'View',
                    ],
                ],
            ],
            [
                'code' => 'request_uri',
                'label' => 'Request URI',
                'type' => 'string',
            ],
            [
                'code' => 'request_url',
                'label' => 'Request URL',
                'type' => 'string',
            ],
        ];
    }

    /**
     * @return mixed|string
     */
    public function getSearchField()
    {
        return 'request_uri';
    }

    /**
     * @return int|mixed
     */
    public function getSearchMethod()
    {
        return self::SEARCH_METHOD_LIKE;
    }

}
