<?php

namespace MobileCart\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository
    extends EntityRepository
    implements CartRepositoryInterface, AdvSortableInterface
{

    /**
     * @return bool
     */
    public function isEAV()
    {
        return true;
    }

    /**
     * @return bool
     */
    public function hasImages()
    {
        return true;
    }

    /**
     * @return array
     */
    public function getSortableFields()
    {
        return [
            'id' => 'ID',
            'created_at' => 'Created At',
            'page_title' => 'Page Title',
            'name' => 'Name',
            'slug' => 'Slug',
        ];
    }

    /**
     * @return array
     */
    public function getAdvSortableFields()
    {
        return [
            'sort_order' => [
                CartRepositoryInterface::LABEL => 'Sort Order',
                'active' => 0,
                'value' => 'sort_order',
                'dir' => 'asc',
            ],
            'name_az' => [
                CartRepositoryInterface::LABEL => 'Name (A-Z)',
                'active' => 0,
                'value' => 'name',
                'dir' => 'asc',
            ],
            'name_za' => [
                CartRepositoryInterface::LABEL => 'Name (Z-A)',
                'active' => 0,
                'value' => 'name',
                'dir' => 'desc',
            ],
            'parent_category' => [
                CartRepositoryInterface::LABEL => 'Parent Category',
                'active' => 0,
                'value' => 'parent_category_id',
                'dir' => 'asc',
            ],
        ];
    }

    /**
     * @return array
     */
    public function getFilterableFields()
    {
        return [
            [
                CartRepositoryInterface::CODE  => 'id',
                CartRepositoryInterface::LABEL => 'ID',
                CartRepositoryInterface::DATATYPE =>  'number',
            ],
            [
                CartRepositoryInterface::CODE  => 'parent_category_id',
                CartRepositoryInterface::LABEL => 'Parent ID',
                CartRepositoryInterface::DATATYPE =>  'number',
            ],
            [
                CartRepositoryInterface::CODE  => 'name',
                CartRepositoryInterface::LABEL => 'Name',
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
            [
                CartRepositoryInterface::CODE  => 'created_at',
                CartRepositoryInterface::LABEL => 'Created At',
                CartRepositoryInterface::DATATYPE =>  'date',
            ],
            [
                CartRepositoryInterface::CODE  => 'sort_order',
                CartRepositoryInterface::LABEL => 'Sort Order',
                CartRepositoryInterface::DATATYPE =>  'number',
            ],
            [
                CartRepositoryInterface::CODE  => 'page_title',
                CartRepositoryInterface::LABEL => 'Page Title',
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
            [
                CartRepositoryInterface::CODE  => 'slug',
                CartRepositoryInterface::LABEL => 'Slug',
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
        ];
    }

    /**
     * @return mixed|string
     */
    public function getSearchField()
    {
        return 'name';
    }

    /**
     * @return int|mixed
     */
    public function getSearchMethod()
    {
        return self::SEARCH_METHOD_LIKE;
    }
}
