<?php

namespace MobileCart\CoreBundle\Repository;

/**
 * ConfigSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigSettingRepository
    extends \Doctrine\ORM\EntityRepository
    implements CartRepositoryInterface
{
    /**
     * @return bool
     */
    public function isEAV()
    {
        return false;
    }

    /**
     * @return bool
     */
    public function hasImages()
    {
        return false;
    }

    /**
     * @return array
     */
    public function getSortableFields()
    {
        return [
            'id' => 'ID',
            CartRepositoryInterface::CODE => CartRepositoryInterface::CODE,
            CartRepositoryInterface::LABEL => CartRepositoryInterface::LABEL,
            'value' => 'Value'
        ];
    }

    /**
     * @return array
     */
    public function getFilterableFields()
    {
        return [
            [
                CartRepositoryInterface::CODE  => 'id',
                CartRepositoryInterface::LABEL => 'ID',
                CartRepositoryInterface::DATATYPE =>  'number',
            ],
            [
                CartRepositoryInterface::CODE => CartRepositoryInterface::CODE,
                CartRepositoryInterface::LABEL => CartRepositoryInterface::CODE,
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
            [
                CartRepositoryInterface::CODE => CartRepositoryInterface::LABEL,
                CartRepositoryInterface::LABEL => CartRepositoryInterface::LABEL,
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
            [
                CartRepositoryInterface::CODE => 'value',
                CartRepositoryInterface::LABEL => 'Value',
                CartRepositoryInterface::DATATYPE =>  'string',
            ]
        ];
    }

    /**
     * @return mixed|string
     */
    public function getSearchField()
    {
        return [CartRepositoryInterface::CODE, CartRepositoryInterface::LABEL, 'value'];
    }

    /**
     * @return int|mixed
     */
    public function getSearchMethod()
    {
        return self::SEARCH_METHOD_LIKE;
    }
}
