<?php

namespace MobileCart\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerAddressRepository
    extends EntityRepository
    implements CartRepositoryInterface
{
    /**
     * @return bool
     */
    public function isEAV()
    {
        return false;
    }

    /**
     * @return bool
     */
    public function hasImages()
    {
        return false;
    }

    /**
     * @return array
     */
    public function getSortableFields()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'company' => 'Company',
            'city' => 'City',
            'region' => 'Region/State',
        ];
    }

    /**
     * @return array
     */
    public function getFilterableFields()
    {
        return [
            [
                'code'  => 'customer_id',
                'label' => 'Customer',
                'datatype' =>  'number',
            ],
            [
                'code'  => 'name',
                'label' => 'Name',
                'datatype' =>  'string',
            ],
            [
                'code'  => 'company',
                'label' => 'Company',
                'datatype' =>  'string',
            ],
            [
                'code'  => 'id',
                'label' => 'ID',
                'datatype' =>  'number',
            ],
            [
                'code'  => 'city',
                'label' => 'City',
                'datatype' =>  'string',
            ],
            [
                'code'  => 'region',
                'label' => 'Region/State',
                'datatype' =>  'string',
            ],
            [
                'code'  => 'country_id',
                'label' => 'Country',
                'datatype' =>  'string',
            ],
        ];
    }

    /**
     * @return mixed|string
     */
    public function getSearchField()
    {
        return ['name', 'company'];
    }

    /**
     * @return int|mixed
     */
    public function getSearchMethod()
    {
        return self::SEARCH_METHOD_LIKE;
    }
}
