<?php

namespace MobileCart\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemVarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemVarRepository
    extends EntityRepository
    implements CartRepositoryInterface
{
    /**
     * @return array
     */
    public function getSortableFields()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            CartRepositoryInterface::CODE => CartRepositoryInterface::CODE,
            'url_token' => 'URL Token',
            CartRepositoryInterface::DATATYPE => 'Data Type',
            'form_input' => 'Form Input',
            'is_required' => 'Is Required',
            'is_displayed' => 'Is Displayed',
            'sort_order' => 'Sort Order',
            'is_facet' => 'Is Facet',
            'is_sortable' => 'Is Sortable',
            'is_searchable' => 'Is Searchable',
        ];
    }

    /**
     * @return array
     */
    public function getFilterableFields()
    {
        return [
            [
                CartRepositoryInterface::CODE  => 'id',
                CartRepositoryInterface::LABEL => 'ID',
                CartRepositoryInterface::DATATYPE =>  'number',
            ],
            [
                CartRepositoryInterface::CODE  => 'name',
                CartRepositoryInterface::LABEL => 'Name',
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
            [
                CartRepositoryInterface::CODE  => CartRepositoryInterface::CODE,
                CartRepositoryInterface::LABEL => CartRepositoryInterface::CODE,
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
            [
                CartRepositoryInterface::CODE  => 'url_token',
                CartRepositoryInterface::LABEL => 'URL Token',
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
            [
                CartRepositoryInterface::CODE  => CartRepositoryInterface::DATATYPE,
                CartRepositoryInterface::LABEL => 'Data Type',
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
            [
                CartRepositoryInterface::CODE  => 'form_input',
                CartRepositoryInterface::LABEL => 'Form Input',
                CartRepositoryInterface::DATATYPE =>  'string',
            ],
            [
                CartRepositoryInterface::CODE  => 'is_facet',
                CartRepositoryInterface::LABEL => 'In Facet',
                CartRepositoryInterface::DATATYPE =>  'boolean',
                'choices' => [
                    [
                        'value' => 0,
                        CartRepositoryInterface::LABEL => 'No',
                    ],
                    [
                        'value' => 1,
                        CartRepositoryInterface::LABEL => 'Yes',
                    ],
                ],
            ],
            [
                CartRepositoryInterface::CODE  => 'is_searchable',
                CartRepositoryInterface::LABEL => 'Is Searchable',
                CartRepositoryInterface::DATATYPE =>  'boolean',
                'choices' => [
                    [
                        'value' => 0,
                        CartRepositoryInterface::LABEL => 'No',
                    ],
                    [
                        'value' => 1,
                        CartRepositoryInterface::LABEL => 'Yes',
                    ],
                ],
            ],
            [
                CartRepositoryInterface::CODE  => 'is_required',
                CartRepositoryInterface::LABEL => 'In Required',
                CartRepositoryInterface::DATATYPE =>  'boolean',
                'choices' => [
                    [
                        'value' => 0,
                        CartRepositoryInterface::LABEL => 'No',
                    ],
                    [
                        'value' => 1,
                        CartRepositoryInterface::LABEL => 'Yes',
                    ],
                ],
            ],
        ];
    }

    /**
     * @return bool
     */
    public function isEAV()
    {
        return false;
    }

    /**
     * @return bool
     */
    public function hasImages()
    {
        return false;
    }

    /**
     * @return mixed|string
     */
    public function getSearchField()
    {
        return 'name';
    }

    /**
     * @return int|mixed
     */
    public function getSearchMethod()
    {
        return self::SEARCH_METHOD_LIKE;
    }
}
