<?php

namespace MobileCart\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemVarOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemVarSetRepository
    extends EntityRepository
    implements CartRepositoryInterface
{
    /**
     * @return array
     */
    public function getSortableFields()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'object_type' => 'Object Type',
        ];
    }

    /**
     * @return array
     */
    public function getFilterableFields()
    {
        return array(
            array(
                CartRepositoryInterface::CODE  => 'id',
                CartRepositoryInterface::LABEL => 'ID',
                CartRepositoryInterface::DATATYPE =>  'number',
            ),
            array(
                CartRepositoryInterface::CODE  => 'name',
                CartRepositoryInterface::LABEL => 'Name',
                CartRepositoryInterface::DATATYPE =>  'string',
            ),
            array(
                CartRepositoryInterface::CODE  => 'object_type',
                CartRepositoryInterface::LABEL => 'Object Type',
                CartRepositoryInterface::DATATYPE =>  'string',
            ),
        );
    }

    /**
     * @return bool
     */
    public function isEAV()
    {
        return false;
    }

    /**
     * @return bool
     */
    public function hasImages()
    {
        return false;
    }

    /**
     * @return mixed|string
     */
    public function getSearchField()
    {
        return 'name';
    }

    /**
     * @return int|mixed
     */
    public function getSearchMethod()
    {
        return self::SEARCH_METHOD_LIKE;
    }
}

